CREATE TABLE "USER_MASTER" 
   (	"USER_ID" NUMBER, 
	"MOBILE_NO" VARCHAR2(12 BYTE), 
	"FNAME" VARCHAR2(50 BYTE), 
	"LNAME" VARCHAR2(50 BYTE), 
	"GENDER" VARCHAR2(1 BYTE), 
	"DOB" VARCHAR2(10 BYTE), 
	"EMAILID" VARCHAR2(100 BYTE), 
	"ADDRESS" VARCHAR2(500 BYTE), 
	"CITY" VARCHAR2(50 BYTE), 
	"COUNTRY" VARCHAR2(50 BYTE), 
	"USER_TYPE" VARCHAR2(20 BYTE), 
	"DATEOFREG" DATE, 
	"UPDATED_DTTM" DATE, 
	"USER_STATUS" VARCHAR2(1 BYTE), 
	"STATUS_REASON" VARCHAR2(500 BYTE), 
	"CHANNEL" VARCHAR2(10 BYTE)
   );
   
   CREATE TABLE "USER_MASTER_HST" 
   (	"USER_ID" NUMBER, 
	"MOBILE_NO" VARCHAR2(12 BYTE), 
	"FNAME" VARCHAR2(50 BYTE), 
	"LNAME" VARCHAR2(50 BYTE), 
	"GENDER" VARCHAR2(1 BYTE), 
	"DOB" VARCHAR2(10 BYTE), 
	"EMAILID" VARCHAR2(100 BYTE), 
	"ADDRESS" VARCHAR2(500 BYTE), 
	"CITY" VARCHAR2(50 BYTE), 
	"COUNTRY" VARCHAR2(50 BYTE), 
	"USER_TYPE" VARCHAR2(20 BYTE), 
	"DATEOFREG" DATE, 
	"UPDATED_DTTM" DATE, 
	"USER_STATUS" VARCHAR2(1 BYTE), 
	"STATUS_REASON" VARCHAR2(500 BYTE), 
	"CHANNEL" VARCHAR2(10 BYTE)
   );
   
   
   CREATE TABLE "PASSWORD_MASTER" 
   (	"USER_ID" NUMBER, 
	"USER_PWD" VARCHAR2(12 BYTE), 
	"PWD1" VARCHAR2(50 BYTE), 
	"PWD2" VARCHAR2(50 BYTE), 
	"PWD3" VARCHAR2(50 BYTE), 
	"DOB" VARCHAR2(10 BYTE), 
	"UPDATED_DTTM" DATE, 
	"TRY_COUNT" NUMBER, 
	"CITY" VARCHAR2(50 BYTE), 
	"LAST_FAULT_DTTM" DATE
   );
   
    CREATE TABLE "OTP_TRACKER" 
   (	"USER_ID" NUMBER, 
	"OTP" VARCHAR2(12 BYTE), 
	"OTP_DTTM" DATE, 
	"TRY_COUNT" NUMBER, 
	"SERVICECODE" VARCHAR2(20 BYTE), 
	"MSG_TEMPLATE_ID" VARCHAR2(20 BYTE), 
	"EMAIL_STATUS" DATE, 
	"SMS_STATUS" NUMBER, 
	"SYSTEM_CUR_MILLIS" VARCHAR2(50 BYTE)
   );
   
    CREATE TABLE "TEMPLATE_MASTER" 
   (	"TEMPLATE_ID" VARCHAR2(12 BYTE), 
	"EMAIL" VARCHAR2(4000 BYTE), 
	"SMS" VARCHAR2(1000 BYTE), 
	"CREATION_DTTM" DATE
   );
   
   CREATE TABLE "INTERESTED_INVESTOR" 
   (	"TMP_ID" NUMBER, 
	"MOBILE_NO" VARCHAR2(12 BYTE), 
	"REQ_DTTM" DATE, 
	"STATUS" VARCHAR2(1 BYTE), 
	"EMAIL_ID" VARCHAR2(100 BYTE), 
	"CHANNEL" VARCHAR2(10 BYTE)
   );
   